version: '2.1'
services:
  mysql:
    image: erdaoya/cloud-data-mysql
    ports:
      - "3306:3306"

  rabbitmq:
    image: rabbitmq:management
    expose:
      - 5672
      - 15672
    ports:
      - "5672:5672"
      - "15672:15672"

  eureka:
    image: erdaoya/cloud-server-discovery
    ports:
      - "9001:9001"
    environment:
      SERVICE_HOST: discovery
      SERVICE_PORT: 9001
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9001/health"]
      interval: 1m30s
      timeout: 10s
      retries: 3

  config:
    image: erdaoya/cloud-server-config
    ports:
      - "9000:9000"
    links:
      - eureka:discovery
      - rabbitmq:rabbitmq
    environment:
      SERVICE_PORT: 9000
      REGISTRY_URL: http://discovery:9001/eureka
    depends_on:
      eureka:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/health"]
      interval: 1m30s
      timeout: 10s
      retries: 3



  zipkin:
    image: erdaoya/cloud-zipkin-ui
    restart: always
    ports:
      - "9012:9012"
    links:
      - eureka:discovery
      - rabbitmq:rabbitmq
    environment:
      SERVICE_PORT: 9012
      REGISTRY_URL: http://discovery:9001/eureka
    depends_on:
      eureka:
        condition: service_healthy

  user:
    image: erdaoya/cloud-service-user
    ports:
      - "9002:9002"
    links:
      - config:config
      - eureka:discovery
      - mysql:db
      - zipkin:zipkin
      - rabbitmq:rabbitmq
    environment:
      SERVICE_PORT: 9002
      REGISTRY_URL: http://discovery:9001/eureka
    depends_on:
      eureka:
        condition: service_healthy
      config:
        condition: service_healthy

  trade:
    image: erdaoya/cloud-service-trade
    ports:
      - "9007:9007"
    links:
      - config:config
      - eureka:discovery
      - mysql:db
      - zipkin:zipkin
      - rabbitmq:rabbitmq
    environment:
      SERVICE_PORT: 9007
      REGISTRY_URL: http://discovery:9001/eureka
    depends_on:
      eureka:
        condition: service_healthy
      config:
        condition: service_healthy
  ext:
    image: erdaoya/cloud-service-client
    ports:
      - "9005:9005"
    links:
      - config:config
      - eureka:discovery
      - user:user
      - trade:trade
      - zipkin:zipkin
      - rabbitmq:rabbitmq
    environment:
      SERVICE_PORT: 9005
      REGISTRY_URL: http://discovery:9001/eureka
    depends_on:
      - eureka
      - config
  gateway:
    image: erdaoya/cloud-api-gateway
    ports:
      - "9006:9006"
    links:
      - config:config
      - eureka:discovery
      - mysql:db
      - user:user
      - trade:trade
      - ext:ext
      - zipkin:zipkin
      - rabbitmq:rabbitmq
    environment:
      SERVICE_PORT: 9006
      REGISTRY_URL: http://discovery:9001/eureka
    depends_on:
      - eureka
      - config

  turbine:
    image: erdaoya/cloud-turbine-dashboard
    ports:
      - "9010:9010"
    links:
      - ext:ext
      - user:user
      - trade:trade
      - eureka:discovery
    environment:
      SERVICE_PORT: 9010
      REGISTRY_URL: http://discovery:9001/eureka
    depends_on:
      - eureka
      - config

  admin:
    image: erdaoya/cloud-admin-ui
    ports:
      - "9003:9003"
    links:
      - turbine:turbine
      - eureka:discovery
    environment:
      SERVICE_PORT: 9003
      REGISTRY_URL: http://discovery:9001/eureka
      TURBINE_URL: http://discovery:9010/turbine.stream
    depends_on:
      - eureka

  comx:
    image: erdaoya/cloud-service-comx
    ports:
      - "9019:9019"
    links:
      - eureka:discovery
    environment:
      SERVICE_PORT: 9019
      REGISTRY_URL: http://discovery:9001/eureka
#    volumes:
#        - "/www:/www"
    depends_on:
      - eureka
      - config
